production:
  adapter: postgresql
  url: postgres://<%= ENV['DB_HOST'] %>/<%= ENV['DB_NAME'] %>

development:
  adapter: postgresql
  url: postgres://<%= ENV['DB_HOST'] %>/<%= ENV['DB_NAME'] %>

test:
  adapter: postgresql
  url: postgres://<%= ENV['DB_HOST'] %>/<%= ENV['DB_NAME'] %>
